name: ACCELQ Automation Run

on:
  push:
    branches: [ "main" ]

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 1: Trigger the ACCELQ CI Job
      - name: Run ACCELQ Test
        uses: accelQ-Inc/accelq-ci-github-actions@v1.4
        with:
          appURL: 'https://app.accelq.io/'
          userName: "phani.yvn@aqsupport.com"
          apiKey: "7wkGaMKar3UOx_ut-n6LedUC9xH6FXHDJr87hPb8JXwaq"
          tenantCode: 'aqsupport'
          jobId: '8852' # Replace with your Job ID
          # Optional: Use -1 to not fail the pipeline if tests fail
          threshold: 0 

      # Step 2: Upload Artifacts
      # Note: ACCELQ typically hosts reports on its own dashboard. 
      # If your job downloads local logs/files, use this step:
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accelq-execution-report
          path: |
            "C:\Users\phani.yvn\ACCELQAgent_1\AgentInstances\agent\user_data\Test.xlsx" # Adjust if you download files via CLI
            **/reports/*.html
