name: ACCELQ Local Combined Job
on: [push]

jobs:
  accelq-test-and-upload:
    runs-on: self-hosted  # Everything now runs on your local Windows machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start ACCELQ Job
        uses: accelQ-Inc/accelq-ci-github-actions@v1.4
        with:
          appURL: 'https://app.accelq.io/'
          userName: "phani.yvn@aqsupport.com"
          apiKey: "7wkGaMKar3UOx_ut-n6LedUC9xH6FXHDJr87hPb8JXwaq"
          tenantCode: 'aqsupport'
          jobId: '8852'
          threshold: 0

      - name: Upload Local Excel to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: accelq-execution-report
          # Note the single quotes and forward slashes for Windows paths in YAML
          path: 'C:/Users/phani.yvn/ACCELQAgent_1/AgentInstances/agent/user_data/Test.xlsx'
